### PR TITLE
Refactor Speech-to-text API for depoyment

### PR DESCRIPTION
**Pull request by zero-nnkn**
## Description
- Update Dockerfile for deployment.
- Separate requirements of dev and prod (local and deploy environment).
- Add test cases.

## Type of change
- [ ] New features (non-breaking change).
- [ ] Bug fix (non-breaking change).
- [x] Breaking change (fix or feature that would cause existing functionality not to work as expected).

## Checklist
- [x] I have performed a self-review of my code.
- [x] I have added thorough tests if it is a core feature.
- [ ] There is a reference to the original bug report and related work.
- [x] I have commented on my code, particularly in hard-to-understand areas.
- [x] The feature is well documented.

### CODE REVIEW

**Comment by zero-nnkn** [comment]
@nxquang-al, please check and edit Dockerfile if you want to run with GPU.

**Review by nxquang-al — APPROVED** [review]
Everything works. The service container is able to use CUDA now.

**Comment by zero-nnkn** [comment]
I update the name to speech-to-text (stt) for consistency.

**Review by nxquang-al — APPROVED** [review]
Deployed successfully.

**Pull request merged**
